Add custom error for when a user adds a type to a scene -- Closes #470
ppb/pursuedpybear pull request #511
Opened 2020-08-22 01:17 UTC by mfonism

This PR adds a cleaner, more descriptive, custom error for when a type is added to a scene, as per #470

2020-08-22 04:45 UTC, mfonism commented
Phew! Finally ready for a review.

Spent a lot of time struggling with (and being baffled at my helplessness to) **"this branch has conflicts that must be resolved"** until I finally realised the default branch is **canon** :mask: .

2020-08-22 12:42 UTC, pathunstrom requested changes
One change for sure, and a minor design question for @astronouth7303 since she did the recent redesign.

2020-08-22 12:42 UTC, pathunstrom commented on ppb/scenes.py
> +    def add(self, child: Hashable, tags: Iterable = ()) -> Hashable:
@astronouth7303 Want your opinion on this, is this the behavior we want on all gom objects at this point, or is it better to leave this as a scene specific thing?

2020-08-22 12:42 UTC, pathunstrom commented on ppb/errors.py
> +    """Raised when a type (opp. an instance object) is used as a child."""
Do me a favor and write out the word instead of abbreviating? It took me entirely too long to parse that one.

2020-08-22 12:42 UTC, pathunstrom commented
We should definitely document that our default branch is canon now. Going to add a ticket for that.

2020-08-22 14:27 UTC, AstraLuma requested changes

2020-08-22 14:27 UTC, AstraLuma commented on ppb/scenes.py
> +        if type(child) is type:
`isinstance(child, type)` would be idiomatic, and it'll catch metaclasses as well.

2020-08-22 14:27 UTC, AstraLuma commented on tests/test_scenes.py
> +    )
I don't think we should be testing the error message?

If you are testing the message, it should not be character-for-character exact--you should test specific meaningful properties (like that it contains the class name).

2020-08-22 21:26 UTC, pathunstrom approved these changes
Looks good now.

2020-08-28 01:03 UTC, AstraLuma approved these changes
bors r+

2020-08-28 02:00 UTC, astronouth7303 commented
bors retry

2020-08-28 02:52 UTC, astronouth7303 commented
sorry, apparently cirrus is being bad today

bors retry

2020-08-28 03:57 UTC, AstraLuma commented
bors retry

2020-08-28 13:42 UTC, AstraLuma commented
bors retry

2020-08-28 14:13 UTC, merged