Fixed references to Ellipse, free(), and load() in Asset System reference
ppb/pursuedpybear pull request #639
Opened 2021-10-01 18:45 UTC by tran-dy

Fixes for issue #607 

Updated the reference to Ellipse and load().
Added the free() method to the Asset reference page to fix the free() hyperlink.

2021-10-02 18:00 UTC, pathunstrom requested changes
This looks fine, we'll skip the system reference itself since we haven't added those docs.

We do need your entry in Contributors.md. Once that's done we can merge!

2021-10-02 19:31 UTC, tran-dy commented
Sounds good, contributors file updated!

2021-10-03 01:13 UTC, pathunstrom requested changes
Tiny formatting change. Added as suggestion feel free to just press the button to accept it.

2021-10-03 01:13 UTC, pathunstrom commented on CONTRIBUTORS.md
> +[Andy Tran](https://github.com/tran-dy) |
```suggestion
[Andy Tran](https://github.com/tran-dy) | | |
```

Quick suggestion so the table doesn't break. Thanks!

2021-10-08 14:59 UTC, pathunstrom approved these changes
Looks good. Thank you for your contribution!

bors r+

2021-10-08 15:10 UTC, pathunstrom commented
Don't worry about the conflict, I'll clean it up as part of our merge process.

2021-10-08 16:34 UTC, pathunstrom commented
bors retry

2021-10-08 17:11 UTC, merged